name: Cronjob

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  TSB_SECRET: ${{ secrets.TSB_SECRET }}
  LAGESO: ${{ secrets.LAGESO }}
  FLUSSHYGIENE_API_HOST: ${{ secrets.FLUSSHYGIENE_API_HOST }}

on:
  repository_dispatch:
    types: [pipedream]
  workflow_dispatch:
  # schedule:
  #   # every day at 5
  #   # https://crontab.guru/#0_5_*_*_*
  #   - cron: "0 5 * * *"

jobs:
  merge_prediction_data:
    runs-on: ubuntu-latest
    name: merging prediction data with data from lageso
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js from nvm
        shell: bash -l {0}
        run: nvm install
      - name: install deps
        run: npm ci
      - name: exec cronjob
        run: node index.js
